-- MySQL Script generated by MySQL Workbench
-- Sun Apr  7 15:08:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema suplemento
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema suplemento
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `suplemento` DEFAULT CHARACTER SET utf8 ;
USE `suplemento` ;

-- -----------------------------------------------------
-- Table `suplemento`.`Stockmanager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suplemento`.`Stockmanager` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `suplemento`.`Carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suplemento`.`Pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `metodoPagamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `suplemento`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suplemento`.`Produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(300) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `quantidade` INT NOT NULL,
  `Pedido_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Produto_Pedido_idx` (`Pedido_id` ASC) ,
  CONSTRAINT `fk_Produto_Pedido`
    FOREIGN KEY (`Pedido_id`)
    REFERENCES `suplemento`.`Pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into Pedido (id,metodoPagamento) values (1 , "Nulo");

INSERT INTO Produto (nome, valor, descricao, quantidade, categoria, Pedido_id)
VALUES ('Whey Protein', 99.90, 'Suplemento de proteína whey concentrada', 50, 'Proteínas', 1),
       ('Albumina', 49.90, 'Suplemento de proteína de alta absorção', 30, 'Proteínas', 1),
       ('Caseína', 79.90, 'Proteína de digestão lenta, ideal para consumo noturno', 40, 'Proteínas', 1);

-- Adicionar produtos de Carboidratos e atribuir Carrinho_id 0
INSERT INTO Produto (nome, valor, descricao, quantidade, categoria, Pedido_id)
VALUES ('Maltodextrina', 29.90, 'Suplemento de carboidrato de rápida absorção', 60, 'Carboidratos', 1),
       ('Dextrose', 19.90, 'Fonte de energia rápida para treinos intensos', 45, 'Carboidratos', 1),
       ('Palatinose', 39.90, 'Carboidrato de baixo índice glicêmico, liberação gradual de energia', 35, 'Carboidratos', 1);

-- Adicionar produtos de Vitaminas e atribuir Carrinho_id 0
INSERT INTO Produto (nome, valor, descricao, quantidade, categoria, Pedido_id)
VALUES ('Multivitamínico', 69.90, 'Suplemento com uma combinação de vitaminas e minerais', 55, 'Vitaminas', 1),
       ('Vitamina C', 29.90, 'Vitamina antioxidante, auxilia na imunidade', 50, 'Vitaminas', 1),
       ('Vitamina D3', 39.90, 'Vitamina essencial para a saúde dos ossos e do sistema imunológico', 40, 'Vitaminas', 1);

-- Adicionar produtos de Aminoácidos e atribuir Carrinho_id 0
INSERT INTO Produto (nome, valor, descricao, quantidade, categoria, Pedido_id)
VALUES ('BCAA', 49.90, 'Aminoácidos de cadeia ramificada, auxilia na recuperação muscular', 60, 'Aminoácidos', 1),
       ('Glutamina', 39.90, 'Aminoácido importante para a saúde intestinal e recuperação muscular', 55, 'Aminoácidos', 1),
       ('Creatina', 59.90, 'Aumenta a energia e a força muscular durante o treinamento', 50, 'Aminoácidos', 1);
       
-- Adicionando mais produtos à tabela Produto
INSERT INTO Produto (nome, descricao, valor, categoria, quantidade, Pedido_id) VALUES
('Whey Protein Isolado', 'Suplemento de proteína whey isolada de alta qualidade', 129.9, 'Proteínas', 45, 1),
('Caseína Micelar', 'Proteína de digestão lenta, ideal para consumo noturno', 89.9, 'Proteínas', 40, 1),
('Massa de Pizza', 'Carboidrato complexo para energia de longa duração', 24.9, 'Carboidratos', 55, 1),
('Barras de Cereal', 'Lanches saudáveis com uma mistura de cereais e frutas secas', 15.9, 'Carboidratos', 65, 1),
('Suplemento de Zinco', 'Mineral essencial para o sistema imunológico e saúde hormonal', 34.9, 'Vitaminas', 30, 1),
('Vitamina B12', 'Importante para o metabolismo energético e função cerebral', 19.9, 'Vitaminas', 60, 1),
('Óleo de Peixe Ômega-3', 'Ácidos graxos essenciais para a saúde cardiovascular e cerebral', 49.9, 'Vitaminas', 40, 1),
('L-Glutamina', 'Aminoácido importante para a recuperação muscular e saúde intestinal', 44.9, 'Aminoácidos', 50, 1),
('BCAA em Pó', 'Aminoácidos essenciais para a síntese proteica e recuperação muscular', 59.9, 'Aminoácidos', 55, 1),
('Creatina Monohidratada', 'Suplemento para aumentar a força e o desempenho durante o treinamento', 69.9, 'Aminoácidos', 45, 1);

-- Adicionando mais produtos à tabela Produto
INSERT INTO Produto (nome, descricao, valor, categoria, quantidade, Pedido_id) VALUES
('Albumina Sabor Chocolate', 'Suplemento de proteína de absorção lenta com sabor de chocolate', 39.9, 'Proteínas', 35, 1),
('Maltodextrina Sabor Limão', 'Suplemento de carboidrato com sabor de limão para energia rápida', 24.9, 'Carboidratos', 50, 1),
('Vitamina D3 em Cápsulas', 'Vitamina essencial em forma de cápsulas para saúde dos ossos e imunidade', 29.9, 'Vitaminas', 45, 1),
('L-Carnitina Líquida', 'Aminoácido que auxilia na queima de gordura e melhora do desempenho físico', 54.9, 'Aminoácidos', 40, 1),
('Cafeína em Pó', 'Estimulante natural que melhora o foco, energia e queima de gordura', 19.9, 'Aminoácidos', 60, 1),
('Barra de Proteína', 'Lanche prático e nutritivo com alto teor de proteína para recuperação muscular', 29.9, 'Proteínas', 55, 1),
('Mix de Vitaminas', 'Suplemento multivitamínico com uma combinação de vitaminas e minerais essenciais', 49.9, 'Vitaminas', 30, 1),
('Proteína Vegana', 'Suplemento de proteína de origem vegetal para dietas veganas e vegetarianas', 64.9, 'Proteínas', 25, 1),
('Glutamina em Cápsulas', 'Aminoácido importante para recuperação muscular e saúde intestinal em cápsulas', 49.9, 'Aminoácidos', 40, 1),
('Suplemento de Ferro', 'Mineral essencial para transporte de oxigênio no sangue e saúde geral', 14.9, 'Vitaminas', 60, 1);

-- Adicionando login e senha 
insert into StockManager (nome,senha) values ("Lucas" , "L123"),("Kauan" , "K123");

select * from produto ;
select * from Pedido;